public static class Names
{
    public static readonly string[] maleNames =
    {
        "Adam",
        "Aiden",
        "Alex",
        "Alphonso",
        "Andrew",
        "Anthony",
        "Benjamin",
        "Barry",
        "Billy",
        "Brett",
        "Brian",
        "Bruce",
        "Bryan",
        "Caleb",
        "Carl",
        "Carlos",
        "Charles",
        "Christopher",
        "Daniel",
        "David",
        "Dean",
        "Deke",
        "Derrick",
        "Dwayne",
        "Edward",
        "Elijah",
        "Elmer",
        "Eric",
        "Eugene",
        "Felix",
        "Finn",
        "Floyd",
        "Frank",
        "Fredrick",
        "Gabriel",
        "Gary",
        "George",
        "Grant",
        "Greg",
        "Harley",
        "Harry",
        "Hector",
        "Henry",
        "Holden",
        "Hunter",
        "Hugo",
        "Iain",
        "Ian",
        "Ignacio",
        "Irwin",
        "Isaac",
        "Ivan",
        "Jack",
        "Jacob",
        "James",
        "Jason",
        "Jeff",
        "Jeffrey",
        "Jenson",
        "John",
        "Karl",
        "Kayden",
        "Kevin",
        "Kris",
        "Kyle",
        "Larry",
        "Lawrence",
        "Lee",
        "Lance",
        "Lenny",
        "Leo",
        "Leon",
        "Liam",
        "Lincoln",
        "Leonard",
        "Lukas",
        "Luke",
        "Mack",
        "Mario",
        "Marcus",
        "Mark",
        "Mason",
        "Murphy",
        "Michael",
        "Nicholas",
        "Nick",
        "Noah",
        "Norbert",
        "Norman",
        "Norris",
        "Oliver",
        "Orlando",
        "Oscar",
        "Otis",
        "Owen",
        "Pablo",
        "Paul",
        "Pete",
        "Peter",
        "Philip",
        "Quentin",
        "Quincy",
        "Quinn",
        "Reginald",
        "Ralph",
        "Randall",
        "Ray",
        "Richard",
        "Ridley",
        "Robert",
        "Sam",
        "Scott",
        "Sean",
        "Sebastian",
        "Simon",
        "Taylor",
        "Ted",
        "Teo",
        "Terry",
        "Thomas",
        "Tim",
        "Tomi",
        "Tony",
        "Vernon",
        "Victor",
        "Vincent",
        "Virgil",
        "Wayne",
        "Wesley",
        "Willard",
        "William",
        "Willie",
        "Wolfe",
        "Xander",
        "Xavier",
        "Zachary",
        "Zane"
    };

    public static readonly string[] femaleNames =
    {
        "Adrianne",
        "Alice",
        "Amanda",
        "Amber",
        "Amy",
        "Anna",
        "Aria",
        "Aurora",
        "Ava",
        "Barbara",
        "Bella",
        "Becky",
        "Betty",
        "Bobbi",
        "Bonnie",
        "Brenda",
        "Camila",
        "Carol",
        "Cathy",
        "Catherine",
        "Charlotte",
        "Cheri",
        "Chloe",
        "Claudia",
        "Daisy",
        "Daphne",
        "Delilah",
        "Diana",
        "Denise",
        "Dorothy",
        "Elena",
        "Elizabeth",
        "Ellen",
        "Emily",
        "Emma",
        "Eva",
        "Esther",
        "Felicia",
        "Fiona",
        "Flora",
        "Florence",
        "Frances",
        "Gabriella",
        "Georgia",
        "Gina",
        "Gloria",
        "Grace",
        "Hannah",
        "Helen",
        "Heather",
        "Hilda",
        "Holly",
        "Ida",
        "Irene",
        "Iris",
        "Isabel",
        "Isabella",
        "Jackie",
        "Jemma",
        "Jennifer",
        "Jessica",
        "Jolie",
        "Josephine",
        "Joy",
        "Judy",
        "Julia",
        "Kaia",
        "Karen",
        "Kate",
        "Kathy",
        "Kerry",
        "Kimberly",
        "Krystal",
        "Lara",
        "Lauren",
        "Lexa",
        "Linda",
        "Lisa",
        "Lorraine",
        "Lucia",
        "Luna",
        "Margaret",
        "Maria",
        "Mary",
        "Melinda",
        "Mia",
        "Molly",
        "Monica",
        "Nancy",
        "Natalia",
        "Natalie",
        "Natasha",
        "Nicole",
        "Nora",
        "Nova",
        "Octavia",
        "Olivia",
        "Olga",
        "Opal",
        "Patricia",
        "Paula",
        "Peggy",
        "Penelope",
        "Rachel",
        "Rebecca",
        "Rita",
        "Rose",
        "Ruby",
        "Samara",
        "Sandra",
        "Sara",
        "Sarah",
        "Scarlett",
        "Seraphina",
        "Sherry",
        "Sky",
        "Sophia",
        "Sue",
        "Tamara",
        "Tasha",
        "Teresa",
        "Tiana",
        "Tina",
        "Toka",
        "Ursula",
        "Valerie",
        "Vicki",
        "Viola",
        "Violet",
        "Virginia",
        "Wendy",
        "Whitney",
        "Wilma",
        "Zaria",
        "Zelma",
        "Zoe"
    };

    public static readonly string[] cave1 = new[]
    {
        "abandoned mine",
        "mossy cave",
        "foggy grotto",
        "dripping cavern",
        "old lair",
    };

    public static readonly string[] cave2 = new[]
    {
        "cave of echoes",
        "dark cave",
        "black grotto",
        "crystal cave",
        "clattering lair"
    };

    public static readonly string[] cave3 = new[]
    {
        "deep maw",
        "dread pit",
        "forgotten abyss",
        "cave of chaos",
        "deadly lair"
    };

    public static readonly string[] dungeon1 = new[]
    {
        "old watchtower",
        "bandit den",
        "shallow crypt",
        "broken cellar",
        "ruined castle",
        "dusty tunnels",
        "old graveyard"
    };

    public static readonly string[] dungeon2 = new[]
    {
        "shadow crypt",
        "ruined catacombs",
        "sunken dungeon",
        "forsaken vault",
        "crypt of ash",
        "labyrinth",
        "tomb of sands",
        "ruined mansion"
    };

    public static readonly string[] dungeon3 = new[]
    {
        "ancient vault",
        "obsidian crypt",
        "bloodstone dungeon",
        "crypt of the nameless",
        "eternal catacombs",
        "crimson castle",
        "dungeon of doom"
    };
}
